# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalpost',
            name='Updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='normalpost',
            name='Timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
