# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170828_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalpost',
            name='Readmore',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
