# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_normalpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalpost',
            name='Image',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
