# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_normalpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='normalpost',
            name='Image',
        ),
    ]
